---
- hosts: SW
  gather_facts: yes
  tasks:
  - name: show vlan brief
    ios_command:
      commands: show vlan brief
    register: result
  - name: save output to local directory
    copy:
          content: "{{ result.stdout | replace('\\n', '\n') }}"          
          dest: "show-output/{{ inventory_hostname }}.ios"
