---
- hosts: SW
  gather_facts: no
  tasks:
  - name: show vlan brief
    ios_command:
      commands: show vlan brief
    register: result
  - name: save collected infromation in data directory
    copy:
      dest: "output.txt"
      content: 
        {{ result.stdout_lines }}
